### ISSUE TITLE
GET = great , now for SET !?

### ISSUE THREAD

**Issue by mrAceT** [Frameright/php-image-metadata-parser#17]
Even though the basic tech for 'regions' has been around for some time, searching for good working implementations is a challenge..

**Thank you for this!**

But (there is almost always one, isn't there ;)

With your tool I can read XMP-regions via PHP, that's nice, but I'dd like to be able to store (and update?) regions also!

Could you make that happen?

**Comment by AurelienLourot** [comment]
Hi @mrAceT, thank you for the interest, great to see others excited about image regions as well. Writing IPTC image regions for all possible image formats is tough and we have decided to stay away from that in PHP for now. Have you tried using [Exiftool](https://github.com/exiftool/exiftool) and/or [PHPExifool](https://github.com/romainneutron/PHPExiftool)? Or if you're just looking for a simple graphical solution for writing crop regions, you can always use https://frameright.app/ . The free tier let's you add upto 5 crop regions per image and supports a bunch of formats.
